### ISSUE TITLE
Add autoplay feature

### ISSUE THREAD

**Issue by erichard** [rbelouin/fip-client#2]
Great FIP client ! I use it as my main music source at home.

The only thing I missing is an autoplay mode. I wish I could bring up the site and don't bother to click on play :-)

**Comment by rbelouin** [comment]
Hey! Thank you for your kind words :)

Yes, this could be an option. Just be aware that it won't work on mobile because of some browser restrictions (actually, that is why the play button exists!).

**Comment by rbelouin** [comment]
14 months later, I'm finally giving this project the little care it deserves :)
Autoplay: done. Thanks again for the suggestion!
